name = "cloudflare"
main = "worker.js"
account_id = "43f94cc4f3beadab0c778fdbb690feb0"
workers_dev = true
compatibility_date = "2025-12-24"

[env.production]
vars = { TELEGRAM_TOKEN = "8360146701:AAFlL3Txjytuh9duj6RGFHjC7-8swU75OsM", CHAT_ID = "5941133676" }

[site]
bucket = "./site"
entry-point = "workers-site"
