name = "jibeman"
main = "worker.js"
compatibility_date = "2025-12-24"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
type = "javascript"

[site]
bucket = "./site"
entry-point = "worker"

# Secret Variable ها از Dashboard اضافه می‌شن
