name = "jibeman"
main = "worker.js"            # فایل Worker اصلی
compatibility_date = "2025-12-24"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

[site]
bucket = "./site"             # مسیر پوشه site/ حاوی HTML و فونت و عکس

# Secret Variable ها را در Dashboard اضافه کن
# TELEGRAM_TOKEN
# CHAT_ID
