name = "cloudflare"
main = "worker.js"   # entry-point به فایل Worker
account_id = "43f94cc4f3beadab0c778fdbb690feb0"
workers_dev = true
compatibility_date = "2025-12-24"

[[kv_namespaces]]
binding = "ASSETS"
id = "YOUR_KV_NAMESPACE_ID"
